In [1]:
import numpy as np
import  pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [2]:
data = pd.read_csv('insurance.csv')
print(data.shape)

(30, 2)


In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
data.head()

age  have_insurance
0   22               0
1   25               0
2   47               1
3   52               0
4   46               1

In [5]:
model = LogisticRegression()
model.fit(data[['age']], data[['have_insurance']])

LogisticRegression()

In [6]:
model.coef_

array([[0.16759302]])

In [7]:
model.intercept_

array([-7.93581903])

In [9]:
#Predict insurance for the age
predictions = model.predict(data[['age']])

#accuracy score
metrics.accuracy_score(predictions, data[['have_insurance']])

0.8333333333333334

In [10]:
data['Prediction']=predictions

In [11]:
data

age  have_insurance  Prediction
0    22               0           0
1    25               0           0
2    47               1           0
3    52               0           1
4    46               1           0
5    56               1           1
6    63               0           1
7    60               1           1
8    62               1           1
9    61               1           1
10   18               0           0
11   28               0           0
12   27               0           0
13   29               0           0
14   49               1           1
15   23               0           0
16   35               0           0
17   55               1           1
18   54               0           1
19   48               1           1
20   58               1           1
21   45               0           0
22   66               1           1
23   65               1           1
24   59               1           1
25   20               0           0
26   31               0           0
27   33               0           0
28   39               0           0
29   50               1           1

In [13]:
model.predict([[47]])

array([0], dtype=int64)

In [14]:
model.predict([[54]])

array([1], dtype=int64)